### ISSUE TITLE
cannot compile the bot

### ISSUE THREAD

**Issue by Vyprath** [PolyMarsDev/Sokobot#1]
I am kinda new to Java, but, I am facing this error upon compiling. 
`Exception in thread "main" java.lang.Error: Unresolved compilation problems: 
	JDABuilder cannot be resolved to a type
	JDABuilder cannot be resolved to a type
	AccountType cannot be resolved to a variable
	OnlineStatus cannot be resolved to a variable
	Activity cannot be resolved

	at Bot.main(Bot.java:16)
`

I believe this is an issue at your end.

**Comment by nekobot64** [comment]
I think this is an issue on your end, I can't replicate it at all, and after fixing the path for the token file, it compiles perfectly fine .w.

What version of Java are you using? The build.gradle says that the bot should be good with Java 8

**Comment by Vyprath** [comment]
I'm using Java 8. I also have gradle through eclipse. I'm trying to edit the src to add some features like automatically detecting when you lose and stuff to pracitse my Java but upon compiling it, I face the error.

I also tried it with a fresh copy of the original source code and I face the same error for some reason.

**Comment by Vyprath** [comment]
The import net cannot be resolved

**Comment by AffluentAvo** [comment]
You need the JDA library. Somehow its not added as a dependency at your end.

**Comment by AffluentAvo** [comment]
Closing this issue as provided solution should fix this problem.
