### ISSUE TITLE
WASD Being Deleted After Game Stopped When an Update Occurs

### ISSUE THREAD

**Issue by dzlandis** [PolyMarsDev/Sokobot#15]
When an update happens with the bot or it goes down, the level stops working and so you need to stop and restart. However, because you were in the middle of the level, even when you start a new game and then end it, the WASD keys are still deleted.
![sokobotdelete](https://user-images.githubusercontent.com/49926644/89585419-aa73e180-d7f2-11ea-8496-245035b569f4.gif)

**Comment by AffluentAvo** [comment]
Will be fixed in just a few minutes :)
EDIT: Fixed (on main bot, not in source code yet)

**Comment by dzlandis** [comment]
Feel free to close this once it is fully fixed. :grin:

**Comment by AffluentAvo** [comment]
Fixed on pull request - you can close this issue
