### ISSUE TITLE
Reactions Deleting

### ISSUE THREAD

**Issue by dzlandis** [PolyMarsDev/Sokobot#16]
If multiple users who are not playing spam the reactions, sometimes it can cause the bot to accidentally remove the reaction completely.
![Screenshot from 2020-08-06 16-24-45](https://user-images.githubusercontent.com/49926644/89592526-a9967c00-d801-11ea-8d70-6e7c9f58f8a7.png)

**Comment by mandar1jn** [comment]
This isn't really a problem since you can just type in the chat boxes, but I will see what I can do with my coming pull request.

**Comment by AffluentAvo** [comment]
This should be fixed now.
Closing issue.
