### ISSUE TITLE
Spamming WASD Can Make the Character Go Through A Block

### ISSUE THREAD

**Issue by dzlandis** [PolyMarsDev/Sokobot#17]
If you spam the WASD keys a lot to move the character quickly, sometimes the character can go through a block and come out the other end instead of pushing it.
![Screenshot from 2020-08-06 16-32-47](https://user-images.githubusercontent.com/49926644/89592850-83bda700-d802-11ea-9186-803cfc0497c7.png)

**Comment by mandar1jn** [comment]
this should be fixed in an update some time ago

**Comment by AffluentAvo** [comment]
This should be fixed. If not, reopen or don't spam too much.
Closing issue.
