### ISSUE TITLE
2 Boxes 1 Green Check Mark

### ISSUE THREAD

**Issue by dzlandis** [PolyMarsDev/Sokobot#18]
[Read The Title]
![Screenshot from 2020-08-06 16-56-15](https://user-images.githubusercontent.com/49926644/89594096-d056b180-d805-11ea-8c1e-54003bd5a354.png)

**Comment by dzlandis** [comment]
It is possible that the user who was playing this game was just inside one of the green check marks. They did not move when I told them to so I don't know. They spawned like this.

**Comment by AffluentAvo** [comment]
Yea that was 100% the case.
You can move through the check marks, and he did move one to the right after he spawned (because he spawned at X=2, Y=2), so that is not really a bug.
Can be closed.

**Comment by dzlandis** [comment]
Okay, thanks.
