### ISSUE TITLE
Offline

### ISSUE THREAD

**Issue by 2qwertyuiop** [PolyMarsDev/Sokobot#20]
i had sokobot for a few days but it suddenly went offline? i didnt do anything to the code or try to hack it. is this a bug or are you taking it down

**Comment by 2qwertyuiop** [comment]
ok its back online. not sure why it went offline in the first place but its back now

**Comment by AffluentAvo** [comment]
Our server provider had some network issues.
You can join the official support server to view Realtime status Updates under `!info`
