### ISSUE TITLE
4 X green block bug

### ISSUE THREAD

**Issue by reero0** [PolyMarsDev/Sokobot#21]
![SharedScreenshot](https://user-images.githubusercontent.com/48021099/89709057-0bcbba00-d985-11ea-8881-2d8246136e26.jpg)

hi i and my friends cant win any lvl with 4 X blocks near the wall because we cant puch the block to win the lvl and we had this problem many time is this a bug or we are missing something thank you

**Comment by AffluentAvo** [comment]
Hello, you can now use `mr` to recreate your map, in case something like that happens.

**Comment by reero0** [comment]
sry but how to use mr ?

**Comment by reero0** [comment]
thank you its working with the mr command

thank you so much
