### ISSUE TITLE
Command To Run In VS Terminal

### ISSUE THREAD

**Issue by ShubanGouru** [PolyMarsDev/Sokobot#23]
Hi, I am unable to find the proper command to get the bot to run in the Visual Studio Terminal. I have tried "node .", without any luck. Would someone be able to tell me what I am supposed to use?

**Comment by a-gt** [comment]
It is written in java. So you would have to do `java bot.jar`

**Comment by ShubanGouru** [comment]
![image](https://user-images.githubusercontent.com/66916946/91625527-153db600-e976-11ea-8ecb-66684ec92dce.png)
Still won't work, am I missing something? @ApexioDaCoder

**Comment by a-gt** [comment]
You have to install java first. Then compile the code into a jar https://github.com/PolyMarsDev/Sokobot#compiling. Then run the jar file produced.

**Comment by a-gt** [comment]
Or you can grab the jar from https://github.com/PolyMarsDev/Sokobot/releases and run it.

**Comment by AffluentAvo** [comment]
Closing issue as it has been resolved.
