### ISSUE TITLE
Can i host it on heroku?

### ISSUE THREAD

**Issue by lmaoguy123** [PolyMarsDev/Sokobot#24]
I can't host it on my computer 24/7 so i need to host it on heroku but i never hosted a bot made on java in heroku help

**Comment by Brocky08** [comment]
You can easily host a javascript bot on Heroku free of charge. Try watching this video. 
https://www.youtube.com/watch?v=8qIsRzV0Hpg&t=448s
Hope this helped, if not I'll be checking for if you need any more help.

**Comment by a-gt** [comment]
The bot is coded in java not javascript.

**Comment by BendyInc** [comment]
You'll need to write a "pom.xml" file before which isn't included in the project. You can learn how to write one and maybe you can get it working.

**Comment by fourteentrees** [comment]
> You can easily host a javascript bot on Heroku free of charge. Try watching this video.
> https://www.youtube.com/watch?v=8qIsRzV0Hpg&t=448s
> Hope this helped, if not I'll be checking for if you need any more help.

This is Java, not JavaScript. The reply above sums up what you need to do.

**Comment by AffluentAvo** [comment]
Closing issue as question have been answered.
