### ISSUE TITLE
Bot doesn't send messages

### ISSUE THREAD

**Issue by ghost** [PolyMarsDev/Sokobot#31]
I tried to see how the bot worked and on my server, it doesn't work. I gave it all perms. 
I think this is because of the commands class in JDA. Also very nice work, JDA is the god language of all bots, it made Dank Memer.

Appreciate this kind of effort. Hope you see through this problem

**Comment by AffluentAvo** [comment]
Hello, do you mean the public bot or did you compile this code to your own Sokobot?

**Comment by ghost** [comment]
I mean the compiled code to my own bot. I am not too fluent at Java and thus do not understand quite some things in the bot. Is there any issue here?

**Comment by AffluentAvo** [comment]
There should not be any issues, however the code might be a bit outdated, compared to the public bot. I will update the code and make a PR later. Sorry!

**Comment by ghost** [comment]
It's fine, although with the public bot the only differences I see are in the structure of the levels and some config stuff. The rest should be working quite fine. I don't see exactly why this won't work. In JDA, most of the stuff is object-oriented thus I should probably have a closer look at the classes.

**Comment by AffluentAvo** [comment]
Sorry I didnt have time to update yet. There are differences to the public bot because I update the public bot way faster, since it is in 24k servers and updates are important. I will try my best to find time to fix the open source code and create a PR.

**Comment by AffluentAvo** [comment]
Code has been update and startup issues fixed. If you still have problems with starting the bot, please reopen this issue.
Closing issue.
