### ISSUE TITLE
two letter won't remove and can't change prefix

### ISSUE THREAD

**Issue by MadzRed** [PolyMarsDev/Sokobot#32]
when i do a two letter command, i can't remove it even after i stop the game. i also can't change the prefix bc in my server, there is 5 bots with the prefix "!"

**Comment by AffluentAvo** [comment]
two letters are not an actual command, so the bot does not recognize this as a message to delete.
also it is not our fault or responsibility what prefixes the other bots have. you can make a channel with only sokobot in it and use it there or make this channel to use the !prefix command to change the prefix server wide.

**Comment by AffluentAvo** [comment]
Closing issue as it has been resolved.

**Comment by MadzRed** [comment]
the issue was that i couldn't delete my message after saying 2 words.
