### ISSUE TITLE
Sokobot doesnt do anything

### ISSUE THREAD

**Issue by AnnoyedArt1256** [PolyMarsDev/Sokobot#34]
help? im using the bot on my test server but it doesnt react to anything really **ANYTHING** idk why it does that. Hope polymars fixes this

**Comment by AffluentAvo** [comment]
I already made a PR for some issues. Waiting for PolyMars to merge

**Comment by AnnoyedArt1256** [comment]
but im using the public version

**Comment by AffluentAvo** [comment]
Then there are multiple possibilities of why it isn't working:

- The shard which contains your server is down (unlikely, try to use the bot on another server tho)
- The bot can't see the channel you are trying to use it
- The bot has not enough permissions to be used. He will tell you that either in the channel or in your DM's, as long as it has permissions to write there.

For the last 2 issues, check the bot's permissions.

**Comment by AnnoyedArt1256** [comment]
hmm it does work on my test server but it doesnt work on my personal server

**Comment by AffluentAvo** [comment]
Then the bot either does not have permissions in your server or the channel you are trying at, or the shard of the bot is down there.
I will check the shards and restart the bot in a few minutes.

**Comment by AnnoyedArt1256** [comment]
but i set all of the permisions on

**Comment by AffluentAvo** [comment]
Please add me on Discord: `Affluent Avo#6099`
I will take a look on that for you

**Comment by AffluentAvo** [comment]
Fixed - bot was not invited to the server. Closing issue.
