### ISSUE TITLE
SLF4J: Failed to load class "org.slf4j.impl.StaticMDCBinder".

### ISSUE THREAD

**Issue by yeojhenrie** [PolyMarsDev/Sokobot#35]
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
SLF4J: Failed to load class "org.slf4j.impl.StaticMDCBinder".
SLF4J: Defaulting to no-operation MDCAdapter implementation.
SLF4J: See http://www.slf4j.org/codes.html#no_static_mdc_binder for further details.
[main] INFO JDA - Login Successful!
[JDA MainWS-WriteThread] INFO WebSocketClient - Connected to WebSocket
SLF4J: Failed to load class "org.slf4j.impl.StaticMDCBinder".

**Comment by AffluentAvo** [comment]
Hello, this issue as described is just a warning by the library we use: JDA
No error itself.
Please refer to their project for more information about that. Closing issue.

**Comment by yeojhenrie** [comment]
ahh so why doesn't it work? I mean I used !play
