### ISSUE TITLE
Bug on sentences

### ISSUE THREAD

**Issue by MrOrange9-JCT** [PolyMarsDev/Sokobot#4]
If you leave a game on, all the sentences that start with `WASD` will be deleted on any channel. This is very annoying for languages like spanish.

**Comment by SpaceR3** [comment]
This can be fixed by Checkin if the current user has a game running. And if the game does not receive any input in 1-2 minutes then it will automatically close the game. I would make a pull request for it but I have never even touched java.

**Comment by MrOrange9-JCT** [comment]
Well, I discovered a new thing, even stopping the game, it will still deleting these sentences.

**Comment by dzlandis** [comment]
An alternative solution is making the game only work in one channel such as #bot-commands. This would solve most of this issue and would be a nice addition as well.

**Comment by MrOrange9-JCT** [comment]
> An alternative solution is making the game only work in one channel such as #bot-commands. This would solve most of this issue and would be a nice addition as well.

Thanks, this works. But i’m not closing this issue.

**Comment by dzlandis** [comment]
I don't seem to be experiencing this issue myself and I am not able to replicate it. Could you provide some screenshots? The project recently got moved to being worked on by Affluent Productions. It is possible that they fixed the issue.

**Comment by AffluentAvo** [comment]
Issue is fixed

**Comment by MrOrange9-JCT** [comment]
Yes, the issue is fixed. Thank you everyone!
