### ISSUE TITLE
The .jar version of the bot runs 3 game instences for one player when !play is exectuted

### ISSUE THREAD

**Issue by KotTheKitty** [PolyMarsDev/Sokobot#40]
# The title say everything

**Comment by KotTheKitty** [comment]
oh, i think i know why it does that. its probably because its running 3 times on my computer. i might just be dumb. however, i cant access the terminalmor close the program in task manager

**Comment by mandar1jn** [comment]
You probably have several instances running indeed. I don't have that problem
