### ISSUE TITLE
Offline

### ISSUE THREAD

**Issue by Llama-Link** [PolyMarsDev/Sokobot#44]
I just watched the video but when I added it to my server it was offline. Please help.

**Comment by CristianEduardMihai** [comment]
Are you sure you ran the .jar and you inputed your bot token, did you enable bot on your discord application?

**Comment by kk5dire** [comment]
Heya, yeah make sure what the person above said, make sure there are no console errors, and that you have the latest verson of java + all the dependencies of the bot, if you get any error that would be very helpful and as always good luck

**Comment by kk5dire** [comment]
> Heya, yeah make sure what the person above said, make sure there are no console errors, and that you have the latest verson of java + all the dependencies of the bot, if you get any error that would be very helpful and as always good luck

it also might be a good idea to update your issue title to more represent your issue as not to be confused with, the public bot being offline

**Comment by AffluentAvo** [comment]
I think @DrJgamingYT meant the public bot.
If you compiled this code or downloaded the .jar-Release and ran the bot on your own system, make sure you provided the right token.
If this still won't help, send us the console output please.

**Comment by kk5dire** [comment]
> I think @DrJgamingYT meant the public bot.
> If you compiled this code or downloaded the .jar-Release and ran the bot on your own system, make sure you provided the right token.
> If this still won't help, send us the console output please.

If so i suggest he just wait

**Comment by AffluentAvo** [comment]
> > I think @DrJgamingYT meant the public bot.
> > If you compiled this code or downloaded the .jar-Release and ran the bot on your own system, make sure you provided the right token.
> > If this still won't help, send us the console output please.
> 
> If so i suggest he just wait

wow your comment was so neccessary

**Comment by mandar1jn** [comment]
The bot should be up again
