### ISSUE TITLE
files

### ISSUE THREAD

**Issue by Nikalitan** [PolyMarsDev/Sokobot#45]
where is the file with the base of the program, where are the answers to commands, and the status in the files?

**Comment by CristianEduardMihai** [comment]
I think the file is `src\main\java\me\polymarsdev\sokobot\Bot.java` or `src\main\java\me\polymarsdev\sokobot\Game.java`

**Comment by mandar1jn** [comment]
src\main\java\me\polymarsdev\sokobot\Bot.java
