### ISSUE TITLE
`Error: Could not find or load main class Bot`

### ISSUE THREAD

**Issue by CristianEduardMihai** [PolyMarsDev/Sokobot#47]
Hi ! I compiled the bot using `./gradlew clean build` and when i run it i get this error:
![image](https://user-images.githubusercontent.com/59600013/117034623-2c565400-ad0c-11eb-84fa-7fa595906fdc.png)
Any ideas why ?
the `Bot` file is still there.
![image](https://user-images.githubusercontent.com/59600013/117034846-5d368900-ad0c-11eb-9f69-3eb1d5d80001.png)

*Looks like i get this error even when i don't modify anything in the source code.

**Comment by AffluentAvo** [comment]
I'm not sure what the gradle part does, however it's `me.polymarsdev.sokobot.Bot`, not just `Bot`

**Comment by CristianEduardMihai** [comment]
> I'm not sure what the gradle part does, however it's `me.polymarsdev.sokobot.Bot`, not just `Bot`

That is literally what i downloaded from github...i tried without changing anything and still got the same error. Is it the same for `Game` ?

**Comment by AffluentAvo** [comment]
Yea, everything is in `me.polymars.dev.sokobot.`. I have to check that out with @PolyMarsDev.

**Comment by CristianEduardMihai** [comment]
> Yea, everything is in `me.polymars.dev.sokobot.`. I have to check that out with @PolyMarsDev.

I changet it and my gradle build failed at :compileJava:..it works only with `Bot.java` and `Game.java`

The same for teamSnake...

**Comment by T0biii** [comment]
have a look at #42 did the fix for me

**Comment by MihaiCristianAlphaTeam** [comment]
Used eclipse instead of gradle
