### ISSUE TITLE
Saving progress 

### ISSUE THREAD

**Issue by CristianEduardMihai** [PolyMarsDev/Sokobot#48]
From what i know, the bot is different from the now offline public bot. Things like prefix/progress saving are not enabled. How can i bring those things back ?

**Comment by kk5dire** [comment]
If the bot is not a self-hosted bot you cant change anything about the current public bot if I am understanding your statement

**Comment by mandar1jn** [comment]
@MihaiCristianAlphaTeam isn’t the bot online again?
