### ISSUE TITLE
Massive amount of changes

### ISSUE THREAD

**Issue by ghost** [PolyMarsDev/Sokobot#5]
So, as a programmer there is alot I'd like to change: 

1. Packaging, having everything in 1 and the same folder gets very messy very quickly, I want to make it so classes are in packages, instead of all in 1
2. Instead of having the bot listen to commands, you'd use [JDA-Utilities](https://github.com/JDA-Applications/JDA-Utilities) to manage this, this would also implement a "EventWaiter" or create a system for saving stuff and a command manager
3. General formatting of code. It's messy in general

**Comment by ghost** [comment]
Ok so, update on this. My IDE (Intellij) does NOT like this repo for some reason. I've only gotten problems with it.
I'm still trying to code what I'm planning

**Comment by ghost** [comment]
I've got to sleep now
This is what I already have
![image](https://user-images.githubusercontent.com/65734638/89111001-17812300-d451-11ea-90f0-c867eb3ec638.png)

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/65734638/89119211-b0915780-d4ac-11ea-8fee-8c1291ec78fb.png)

**Comment by Xeravax** [comment]
Due to not getting any response and another pull request already fixing most of the problems. This issue can be closed

**Comment by AffluentAvo** [comment]
Closing issues as current code has been improved with another PR.
