### ISSUE TITLE
Sometimes Doesen't go when typing w a s or d if you type to fast

### ISSUE THREAD

**Issue by Jeremyofishail** [PolyMarsDev/Sokobot#50]
Please patch

**Comment by mandar1jn** [comment]
That is because it can’t handle those speeds

**Comment by kk5dire** [comment]
I think this is just a rate limiting issue which cannot be changed as it is put in place by discord to protect its users

**Comment by mandar1jn** [comment]
indeed

**Comment by thrailkillr** [comment]
> protect its users

*prevent the servers from exploding from stress
