### ISSUE TITLE
Sokobot went offline

### ISSUE THREAD

**Issue by hh12github** [PolyMarsDev/Sokobot#52]
I do not know what happened but...
![sokoman](https://user-images.githubusercontent.com/76072730/120942956-07357680-c6fa-11eb-9964-19bef114d7ea.png)

**Comment by mandar1jn** [comment]
Polymarsdev took it offline. Please close this. It is online again

**Comment by TechStudent10** [comment]
Not anymore #57

**Comment by AffluentAvo** [comment]
Official Sokobot is offline atm.
