### ISSUE TITLE
change the player

### ISSUE THREAD

**Issue by 5alidshammout** [PolyMarsDev/Sokobot#53]
https://github.com/PolyMarsDev/Sokobot/blob/aeac78c2adf629364a6480f1ee94867b19100204/src/main/java/me/polymarsdev/sokobot/Game.java#L15
make the bot upload a player as emoji, and it uses it as the player, and everything will be looking nice

**Comment by kk5dire** [comment]
I believe you can if you vote for the bot, if I am understanding you

**Comment by AffluentAvo** [comment]
You can use other emotes by typing an emote after the `play` command, like `<prefix>play :smile:`
