### ISSUE TITLE
WASD Spam & Reactions Not Removing After Pressed

### ISSUE THREAD

**Issue by dzlandis** [PolyMarsDev/Sokobot#8]
In the recent update of the game, the WASD commands do not delete after they are typed. Thus, leaving a trail of the keys you pressed in the channel. I am wondering why the deleting feature was removed. Am I the only one experiencing this issue? 

https://i.imgur.com/s8Jzud3.png

**Comment by dzlandis** [comment]
This issue seems to have been fixed so I will now be closing it.

**Comment by dzlandis** [comment]
I spoke to soon. It seemed to be working for a bit but when I closed and reopened the game, the issue came back.
![Screenshot from 2020-08-06 13-16-14](https://user-images.githubusercontent.com/49926644/89578478-0c2e4e80-d7e7-11ea-8c59-960e74f16c15.png)

**Comment by dzlandis** [comment]
After some more testing, the issue also seems to be happening with the reaction controls as well. The reactions do not remove themselves like they should after being pressed. It seems like this glitch has mostly to do with removing things the user does.

**Comment by dzlandis** [comment]
Upon further testing, the issue fixed itself after a while. I will still keep this opened as I am unsure if this is just luck or the bug was quickly resolved.

**Comment by thewilloftheshadow** [comment]
Maybe make sure that the bot has the "Manage Messages" permission in the channel you're using it in, since Discord requires that for deleting both reactions and messages

**Comment by AffluentAvo** [comment]
Fixed. Some messages might stay due to discord bugs or too fast responses, however this is just a visual bug. Reloading discord clears those messages.

**Comment by dzlandis** [comment]
Okay. Closing.
