### ISSUE TITLE
Deletes messages when no game is running

### ISSUE THREAD

**Issue by sussycatgirl** [PolyMarsDev/Sokobot#9]
The bot deletes all messages that only contain "w", "a", "s" or "d", even if no game is running.

![P0DvYnymsd](https://user-images.githubusercontent.com/26145882/89213472-7071c800-d5c5-11ea-859f-1ccb1ff2efbc.gif)

**Comment by a-gt** [comment]
Same

**Comment by dzlandis** [comment]
I believe this bug was fixed or was a temporary glitch. The bot is now being run by Affluent Productions so I think they fixed a lot of these issues. I don't seem to have this issue anymore. I would suggest closing this issue.

**Comment by sussycatgirl** [comment]
Yes, seems to be fixed now.
